[package]
name = "hook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
macros = { path = "../macros" }
sdk = { path = "../sdk" }
windows.workspace = true
